name: youtube_downloader
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  youtube_explode_dart: ^2.2.1
  shared_preferences: ^2.2.3
  file_picker: ^8.0.3
  flutter_background_service: ^5.0.6
  flutter_local_notifications: ^17.1.2
  flutter_background_service_android: ^6.2.3


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/youtube_downloader.html


  uses-material-design: true

